Update test.yml

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -15,26 +15,23 @@ on:
 
 # A workflow run is made up of one or more jobs that can run sequentially or in parallel
 jobs:
-  build-and-test:
+  job1:
+    name: Job 1
     runs-on: ubuntu-latest
+
     steps:
-    - uses: actions/checkout@v2
-
-    # Mock to test workflow
-    - name: Test app
-      id: test-app # will be referenced later
+    - name: Sleep and Run
       run: |
-        echo "Testing app (randomly fails)"
-        if [[ $(($RANDOM % 2)) == 0 ]]; then exit 0; else exit 1; fi
+        echo "Sleeping for 10"
+        sleep 10
 
-    # runs always
-    - name: test-clean
-      if: always()
-      run: echo "Cleanup after tests"
+  job2:
+    name: Job 2
+    needs: job1
+    runs-on: ubuntu-latest
 
-    # runs if previous jobs failed and test-app was not successful (failure/cancelled)
-    - name: action-slack
-      if: failure() && steps.test-app.outcome != 'success'
+    steps:
+    - name: Dependant is Running
       run: |
-        echo "Run action-slack"
-        echo "Result of test-app was '${{ steps.test-app.outcome }}'"
+        echo "Completed job 2, but triggering failure"
+        exit 1
